name: Svelte library pull requests
on:
    pull_request:
        branches:
            - main
jobs:
    svelte-library:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                version: ['16.x', '18.x']
        steps:
            - name: Checkout svelte library repository
              uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node_version }}
                  registry-url: 'https://registry.npmjs.org'
            - run: npm ci
            - name: Check lint errors
              run: npm run lint
            - name: Run unit tests
              run: npm run test
            - name: Run e2e tests
              run: |
                  npm run build
                  npm run preview &
                  npm run e2e:ci
